export const ItemRequestStatus = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  PARTIALLY_APPROVED: 'PARTIALLY_APPROVED',
  APPROVED: 'APPROVED',
  PARTIALLY_DELIVERED: 'PARTIALLY_DELIVERED',
  DELIVERED: 'DELIVERED',
  PENDING_INVOICE: 'PENDING_INVOICE',
  COMPLETED: 'COMPLETED',
  DISAPPROVED: 'DISAPPROVED'
} as const;

export type ItemRequestStatus = keyof typeof ItemRequestStatus;
